#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jul 13 12:35:51 -03 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim counter_tb_behav -key {Behavioral:sim_counter:Functional:counter_tb} -tclbatch counter_tb.tcl -view /home/jb/fpga/soundfx/counter_tb.wcfg -log simulate.log"
xsim counter_tb_behav -key {Behavioral:sim_counter:Functional:counter_tb} -tclbatch counter_tb.tcl -view /home/jb/fpga/soundfx/counter_tb.wcfg -log simulate.log

