#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2023.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jul 06 20:10:03 -03 2023
# SW Build 3865809 on Sun May  7 15:04:56 MDT 2023
#
# IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim i2c_tb_behav -key {Behavioral:sim_i2c:Functional:i2c_tb} -tclbatch i2c_tb.tcl -view /home/jb/fpga/soundfx/i2c_tb.wcfg -log simulate.log"
xsim i2c_tb_behav -key {Behavioral:sim_i2c:Functional:i2c_tb} -tclbatch i2c_tb.tcl -view /home/jb/fpga/soundfx/i2c_tb.wcfg -log simulate.log

